openai:
  model: "gpt-5-mini"
  embeddings_model: "text-embedding-3-small"
  api_key: "YOUR_OPENAI_API_KEY"
  base_url: "https://api.openai.com/v1/"
  timeout_ms: 12000
  reasoning_effort: "low" # Válido: low, medium, high
  # Decidir o "temperamento" do assistente, sendo um número menor mais conservador e um número maior mais criativo. (0 a 1)
  temperature: 0.2
  # Quantidade máxima de ‘tokens’ que a resposta pode ter
  max_completion_tokens: 512
  # Usado para ajudar a OpenAI a monitorar e identificar abuso
  user: "ShiftAssistant v1 - Your server name"

history:
  max_messages: 10
  max_tokens: 2048
  max_age_seconds: 7200 # 2 horas
  cleanup_interval_seconds: 30 # Tempo em segundos entre as limpezas do histórico de mensagens

retrieval:
  top_k: 6
  min_cosine: 0.78
  max_chunk_chars: 1800

prompt:
  # Sendo knowledge o resultado da pesquisa RAG pelo banco de informações e live_prompt a resposta depois do parse do placeholder api
  base_prompt: "Você deve apenas responder com informações de seu banco de conhecimento e dados em tempo real, caso contrário, fale que desconhece a resposta.
    Você não deve usar o formato Markdown, apenas texto simples.
    Base de conhecimentos: {{knowledge}}
    Dados em tempo real: {{extra_prompt}}"
  # Supports placeholder api
  extra_prompt: "Nick: %player_name% Dinheiro: %player_money% Pontos: %player_points% Nível: %player_level%"

rate_limits:
  per_player_qpm: 6
  per_server_qpm: 120