openai:
  model: "gpt-4.1-mini"
  embeddings_model: "text-embedding-3-small"
  api_key: "YOUR_OPENAI_API_KEY"
  base_url: "https://api.openai.com/v1/"
  timeout_ms: 12000
  reasoning_effort: "no_reasoning" # Válido: low, medium, high, no_reasoning
  # Decidir o "temperamento" do assistente, sendo um número menor mais conservador e um número maior mais criativo. (0 a 1)
  temperature: 0.2
  # Quantidade máxima de ‘tokens’ que a resposta pode ter.
  max_completion_tokens: 8192
  # Usado para ajudar a OpenAI a monitorar e identificar abuso
  user: "ShiftAssistant v1 - Your server name"

history:
  max_messages: 10
  max_tokens: 16384
  max_age_seconds: 7200 # 2 horas
  # Tempo em segundos entre as limpezas do histórico de mensagens
  cleanup_interval_seconds: 30

retrieval:
  top_k: 6
  min_cosine: 0.70
  max_chunk_chars: 500

prompt:
  # Sendo knowledge o resultado da pesquisa RAG pelo banco de informações e live_prompt a resposta depois do parse do placeholder api
  base_prompt: "Você deve sempre formatar o texto usando MiniMessage em vez de Markdown.
    Nunca use Markdown, asteriscos ou backticks. 
    Use apenas tags MiniMessage para cores, estilos e formatação.
    Lembre, MiniMessage não é html, então não use tags html.
    Exemplo: <red>Texto em vermelho</red>, <bold>negrito</bold>, <gradient:blue:green>gradiente</gradient>.
    
    Base de conhecimentos: {{knowledge}}
    Dados em tempo real: {{extra_prompt}}"
  # Supports placeholder api
  extra_prompt: "Nick: %player_name% Dinheiro: %player_money% Pontos: %player_points% Nível: %player_level%"

rate_limits:
  per_player_qpm: 6
  per_server_qpm: 120