name: ShiftAssistant
version: '1.0.0'
main: dev.shiftsad.shiftAssistant.ShiftAssistant
api-version: '1.20'
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true